[package]
name = "igloo-connector-filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
igloo-common = { path = "../../common" }
tokio = { version = "1", features = ["full"] }
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
