[package]
name = "igloo-client"
version = "0.1.0"
edition = "2021"

[dependencies]
igloo-api = { path = "../api" }
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
prost = "0.13"
prost-types = "0.13"
