[package]
name = "igloo-client"
version = "0.1.0"
edition = "2021"

[dependencies]
igloo-api = { path = "../api" }
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
