[package]
name = "igloo-client"
version = "0.1.0"
edition = "2021"

[dependencies]
igloo-api = { path = "../../api" }
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
arrow-flight = "0.10.0"
anyhow = "1.0"
tokio-stream = "0.1"
rustyline = "13.0.0"
prettytable-rs = "0.10.0"
arrow = { version = "35.0.0", features = ["ipc"] } # Matched to arrow-flight's dependency
clap = { version = "4.4.8", features = ["derive"] } # Added clap
# rustyline-derive = "0.9.0" # Optional, for helpers if needed later
