[package]
name = "igloo-connector-mysql"
version = "0.1.0"
edition = "2021"

[dependencies]
igloo-common = { path = "../../common" }
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
prost = "0.13"
prost-types = "0.13"
